package lt.rokas.uzd1.mybatis.dao;

import java.util.List;
import lt.rokas.uzd1.mybatis.model.Expensegrouptag;
import org.mybatis.cdi.Mapper;

@Mapper
public interface ExpensegrouptagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EXPENSEGROUPTAG
     *
     * @mbg.generated Mon May 03 19:35:03 EEST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EXPENSEGROUPTAG
     *
     * @mbg.generated Mon May 03 19:35:03 EEST 2021
     */
    int insert(Expensegrouptag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EXPENSEGROUPTAG
     *
     * @mbg.generated Mon May 03 19:35:03 EEST 2021
     */
    Expensegrouptag selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EXPENSEGROUPTAG
     *
     * @mbg.generated Mon May 03 19:35:03 EEST 2021
     */
    List<Expensegrouptag> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EXPENSEGROUPTAG
     *
     * @mbg.generated Mon May 03 19:35:03 EEST 2021
     */
    int updateByPrimaryKey(Expensegrouptag record);
}