package lt.rokas.uzd1.mybatis.dao;

import java.util.List;
import lt.rokas.uzd1.mybatis.model.ExpenseGroup;
import lt.rokas.uzd1.mybatis.model.ExpenseGroupTag;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface ExpenseGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EXPENSEGROUP
     *
     * @mbg.generated Mon May 03 19:35:03 EEST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EXPENSEGROUP
     *
     * @mbg.generated Mon May 03 19:35:03 EEST 2021
     */
    int insert(ExpenseGroup record);

    int addGroupTag(@Param("group") ExpenseGroup record, @Param("tag") ExpenseGroupTag tag);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EXPENSEGROUP
     *
     * @mbg.generated Mon May 03 19:35:03 EEST 2021
     */
    ExpenseGroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EXPENSEGROUP
     *
     * @mbg.generated Mon May 03 19:35:03 EEST 2021
     */
    List<ExpenseGroup> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EXPENSEGROUP
     *
     * @mbg.generated Mon May 03 19:35:03 EEST 2021
     */
    int updateByPrimaryKey(ExpenseGroup record);
}