package lt.rokas.uzd1.mybatis.dao;

import java.util.List;
import lt.rokas.uzd1.mybatis.model.Expensegroup;
import lt.rokas.uzd1.mybatis.model.Expensegrouptag;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface ExpensegroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EXPENSEGROUP
     *
     * @mbg.generated Mon May 03 19:35:03 EEST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EXPENSEGROUP
     *
     * @mbg.generated Mon May 03 19:35:03 EEST 2021
     */
    int insert(Expensegroup record);

    int addGroupTag(@Param("group") Expensegroup record, @Param("tag") Expensegrouptag tag);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EXPENSEGROUP
     *
     * @mbg.generated Mon May 03 19:35:03 EEST 2021
     */
    Expensegroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EXPENSEGROUP
     *
     * @mbg.generated Mon May 03 19:35:03 EEST 2021
     */
    List<Expensegroup> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EXPENSEGROUP
     *
     * @mbg.generated Mon May 03 19:35:03 EEST 2021
     */
    int updateByPrimaryKey(Expensegroup record);
}