package lt.rokas.uzd1.mybatis.dao;

import java.util.List;
import lt.rokas.uzd1.mybatis.model.ExpenseGroupTag;
import org.mybatis.cdi.Mapper;

@Mapper
public interface ExpenseGroupTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EXPENSEGROUPTAG
     *
     * @mbg.generated Mon May 03 19:35:03 EEST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EXPENSEGROUPTAG
     *
     * @mbg.generated Mon May 03 19:35:03 EEST 2021
     */
    int insert(ExpenseGroupTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EXPENSEGROUPTAG
     *
     * @mbg.generated Mon May 03 19:35:03 EEST 2021
     */
    ExpenseGroupTag selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EXPENSEGROUPTAG
     *
     * @mbg.generated Mon May 03 19:35:03 EEST 2021
     */
    List<ExpenseGroupTag> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EXPENSEGROUPTAG
     *
     * @mbg.generated Mon May 03 19:35:03 EEST 2021
     */
    int updateByPrimaryKey(ExpenseGroupTag record);
}