package lt.rokas.uzd1.mybatis.dao;

import java.util.List;
import lt.rokas.uzd1.mybatis.model.Expense;
import org.mybatis.cdi.Mapper;

@Mapper
public interface ExpenseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EXPENSE
     *
     * @mbg.generated Mon May 03 19:35:03 EEST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EXPENSE
     *
     * @mbg.generated Mon May 03 19:35:03 EEST 2021
     */
    int insert(Expense record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EXPENSE
     *
     * @mbg.generated Mon May 03 19:35:03 EEST 2021
     */
    Expense selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EXPENSE
     *
     * @mbg.generated Mon May 03 19:35:03 EEST 2021
     */
    List<Expense> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EXPENSE
     *
     * @mbg.generated Mon May 03 19:35:03 EEST 2021
     */
    int updateByPrimaryKey(Expense record);
}