package lt.rokas.uzd1.mybatis.model;

import java.util.Date;
import java.util.List;

public class ExpenseGroup {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EXPENSEGROUP.ID
     *
     * @mbg.generated Mon May 03 19:35:03 EEST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EXPENSEGROUP.DATE
     *
     * @mbg.generated Mon May 03 19:35:03 EEST 2021
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EXPENSEGROUP.DESCRIPTION
     *
     * @mbg.generated Mon May 03 19:35:03 EEST 2021
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EXPENSEGROUP.NAME
     *
     * @mbg.generated Mon May 03 19:35:03 EEST 2021
     */
    private String name;

    public List<Expense> expenses;

    public Double totalCost;

    public List<ExpenseGroupTag> expenseGroupTags;

    public List<ExpenseGroupTag> getExpenseGroupTags() {
        return expenseGroupTags;
    }

    public void setExpenseGroupTags(List<ExpenseGroupTag> expenseGroupTags) {
        this.expenseGroupTags = expenseGroupTags;
    }

    public Double getTotalCost() {
        return totalCost;
    }

    public void setTotalCost(Double totalCost) {
        this.totalCost = totalCost;
    }

    public List<Expense> getExpenses() {
        return expenses;
    }

    public void setExpenses(List<Expense> expenses) {
        this.expenses = expenses;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EXPENSEGROUP.ID
     *
     * @return the value of PUBLIC.EXPENSEGROUP.ID
     *
     * @mbg.generated Mon May 03 19:35:03 EEST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EXPENSEGROUP.ID
     *
     * @param id the value for PUBLIC.EXPENSEGROUP.ID
     *
     * @mbg.generated Mon May 03 19:35:03 EEST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EXPENSEGROUP.DATE
     *
     * @return the value of PUBLIC.EXPENSEGROUP.DATE
     *
     * @mbg.generated Mon May 03 19:35:03 EEST 2021
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EXPENSEGROUP.DATE
     *
     * @param date the value for PUBLIC.EXPENSEGROUP.DATE
     *
     * @mbg.generated Mon May 03 19:35:03 EEST 2021
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EXPENSEGROUP.DESCRIPTION
     *
     * @return the value of PUBLIC.EXPENSEGROUP.DESCRIPTION
     *
     * @mbg.generated Mon May 03 19:35:03 EEST 2021
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EXPENSEGROUP.DESCRIPTION
     *
     * @param description the value for PUBLIC.EXPENSEGROUP.DESCRIPTION
     *
     * @mbg.generated Mon May 03 19:35:03 EEST 2021
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EXPENSEGROUP.NAME
     *
     * @return the value of PUBLIC.EXPENSEGROUP.NAME
     *
     * @mbg.generated Mon May 03 19:35:03 EEST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EXPENSEGROUP.NAME
     *
     * @param name the value for PUBLIC.EXPENSEGROUP.NAME
     *
     * @mbg.generated Mon May 03 19:35:03 EEST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

}