package lt.rokas.uzd1.mybatis.model;

import java.util.Objects;

public class Expensegrouptag {

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EXPENSEGROUPTAG.ID
     *
     * @mbg.generated Mon May 03 19:35:03 EEST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EXPENSEGROUPTAG.NAME
     *
     * @mbg.generated Mon May 03 19:35:03 EEST 2021
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EXPENSEGROUPTAG.ID
     *
     * @return the value of PUBLIC.EXPENSEGROUPTAG.ID
     *
     * @mbg.generated Mon May 03 19:35:03 EEST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EXPENSEGROUPTAG.ID
     *
     * @param id the value for PUBLIC.EXPENSEGROUPTAG.ID
     *
     * @mbg.generated Mon May 03 19:35:03 EEST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EXPENSEGROUPTAG.NAME
     *
     * @return the value of PUBLIC.EXPENSEGROUPTAG.NAME
     *
     * @mbg.generated Mon May 03 19:35:03 EEST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EXPENSEGROUPTAG.NAME
     *
     * @param name the value for PUBLIC.EXPENSEGROUPTAG.NAME
     *
     * @mbg.generated Mon May 03 19:35:03 EEST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Expensegrouptag that = (Expensegrouptag) o;
        return Objects.equals(id, that.id);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id);
    }

}