package lt.rokas.uzd1.mybatis.model;

public class Expense {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EXPENSE.ID
     *
     * @mbg.generated Mon May 03 19:35:03 EEST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EXPENSE.COST
     *
     * @mbg.generated Mon May 03 19:35:03 EEST 2021
     */
    private Double cost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EXPENSE.NAME
     *
     * @mbg.generated Mon May 03 19:35:03 EEST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EXPENSE.EXPENSEGROUP_ID
     *
     * @mbg.generated Mon May 03 19:35:03 EEST 2021
     */
    private Integer expensegroupId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EXPENSE.ID
     *
     * @return the value of PUBLIC.EXPENSE.ID
     *
     * @mbg.generated Mon May 03 19:35:03 EEST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EXPENSE.ID
     *
     * @param id the value for PUBLIC.EXPENSE.ID
     *
     * @mbg.generated Mon May 03 19:35:03 EEST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EXPENSE.COST
     *
     * @return the value of PUBLIC.EXPENSE.COST
     *
     * @mbg.generated Mon May 03 19:35:03 EEST 2021
     */
    public Double getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EXPENSE.COST
     *
     * @param cost the value for PUBLIC.EXPENSE.COST
     *
     * @mbg.generated Mon May 03 19:35:03 EEST 2021
     */
    public void setCost(Double cost) {
        this.cost = cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EXPENSE.NAME
     *
     * @return the value of PUBLIC.EXPENSE.NAME
     *
     * @mbg.generated Mon May 03 19:35:03 EEST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EXPENSE.NAME
     *
     * @param name the value for PUBLIC.EXPENSE.NAME
     *
     * @mbg.generated Mon May 03 19:35:03 EEST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EXPENSE.EXPENSEGROUP_ID
     *
     * @return the value of PUBLIC.EXPENSE.EXPENSEGROUP_ID
     *
     * @mbg.generated Mon May 03 19:35:03 EEST 2021
     */
    public Integer getExpensegroupId() {
        return expensegroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EXPENSE.EXPENSEGROUP_ID
     *
     * @param expensegroupId the value for PUBLIC.EXPENSE.EXPENSEGROUP_ID
     *
     * @mbg.generated Mon May 03 19:35:03 EEST 2021
     */
    public void setExpensegroupId(Integer expensegroupId) {
        this.expensegroupId = expensegroupId;
    }
}